comment:
  # show component info in the PR comment
  layout: "header, diff, files, components"
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 20%
    patch:
      default:
        informational: true
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

component_management:
  individual_components:
    # component_id is an identifier that should not be changed
    # name is a display name, and can be changed freely
    - component_id: client_website
      name: Website
      paths:
        - client/**
    - component_id: lib_ms
      name: Lib Microservice
      paths:
        - servers/lib/**
