yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

extends: default

rules:
  document-start:
    present: false
  truthy:
    allowed-values: ['TRUE', 'True', 'true', 'FALSE', 'False', 'false']
    check-keys: true
