# This is the config for DTaaS CLI

name = "Digital Twin as a Service (DTaaS)"
version = "0.1.1"
owner = "The INTO-CPS-Association"
git-repo = "https://github.com/into-cps-association/DTaaS.git"

[common]
# absolute path to the DTaaS application directory
server-dns = "localhost"
# Specify the directory of DTaaS installation
# Linux example
path = "/home/Desktop/DTaaS"
# Windows example
#path = "C:\\Users\\XXX\\DTaaS"
# Note: You have to either use / or \\ when specifying path, else you would get 
# "Error while getting toml file: dtaas.toml, Invalid unicode value"

[users]
# matching user info must present in this config file
add = ["username1","username2", "username3"] 
delete = ["username2", "username3"]

[users.username1]
email = "username1@gitlab.foo.com"

[users.username2]
email = "username2@gitlab.foo.com"

[users.username3]
email = "username3@gitlab.foo.com"

[client.web]
config = "/home/Desktop/DTaaS/env.local.js"
